-- fintech-payments schema (payment_db)
CREATE TABLE IF NOT EXISTS payments (
  id CHAR(36) PRIMARY KEY,
  wallet_id CHAR(36) NOT NULL,
  user_id CHAR(36) NOT NULL,
  amount BIGINT NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  gateway VARCHAR(50) NOT NULL DEFAULT 'nexpay',
  status ENUM('PENDING','SUCCESS','FAILED') NOT NULL DEFAULT 'PENDING',
  reference VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
  id CHAR(36) PRIMARY KEY,
  payment_id CHAR(36) NOT NULL,
  gateway_transaction_id VARCHAR(255),
  status ENUM('PENDING','SUCCESS','FAILED') NOT NULL,
  response JSON,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_transactions_payment (payment_id)
);
